### ISSUE TITLE
Support latest IOTA JavaScript client library

### ISSUE THREAD

**Issue by jserv** [DLTcollab/raam.client.js#1]
The latest version of package `@iota/core` is `1.0.0-beta.12`, which conflicts with RAAM:
```shell
$ node examples/manualMessageConstruction.js
...
Getting message...
Bundle RDG9INNRSGYKJCBUWGRKAELCKUXLMWA9EQVKS9KVESYLSBLCPJLLQKKRGCZINECXZLPJYGFBRLTBPSB9W - RangeError: Source is too large
    at Int8Array.set (<anonymous>)
    at processBundle (raam.client.js/lib/message.js:261:26)
    at Object.getMessage (raam.client.js/lib/message.js:176:30)
TypeError: Cannot read property 'index' of undefined
    at examples/manualMessageConstruction.js:66:34
```

It works well when `@iota/core` is rolled back to version "1.0.0-beta.11"

**Comment by jserv** [comment]
Close via #2
