### ISSUE TITLE
Failed to fetch the message when running simpleReadWrite example

### ISSUE THREAD

**Issue by ender503** [DLTcollab/raam.client.js#3]
```bash
$ node examples/simpleReadWrite.js 
Seed: BXQILBEHWEGCMUIGRJSJFQKNRPUEJHCH9ZGJZVQTNUMSZ9CDFQDVUXJXFRHQDYUVXKRYV9TTKJORG9IUL
Channel root: CHZSXYPOZINNMHBUHFPCSOWXTWVAQVINYPEFFFPDTHKOOZJQAUOE9ZURTDOFEVZEQXUZCDJKIZDVOUFBCSMGXECZ9FOURVZYD9JTVYOEHMRDJLGCGOBEXMOJUHEXKAAENV9UVVQYUQNMJJWUKMIEAODM9LXAEZUX9W
Generated RAAM channel. Reading channel...
Cursor: 0
Messages: []
Publishing 2 messages...
Bundle 1: TKJIDKLY9FDPEFQXHLFILBVJL9OBWG9IRVCEFYZGJ9GFQVYAZCGJHPYYKKONOGKTCOLBEIFATYKEDHEJD
Bundle 2: FIYZEAIAGJRREHLZPISVGEPBVKCWBBDYJATZIVVO9DGKETJCWLXCGAGYCGFJKYQFIYSOJS9ARUZEDCLNW
Messages: [ 'HELLOIOTA', <2 empty items>, 'HELLOIOTAA' ]
Branch security: 1
Branch messages: []
Messages: []
Bundle 3: UXQQYLIKUUWL9KFPFWXNKQCKQINDFEXLB9CHNVUY9VGQLDUAXWVHLQHK9YAYVLJJHVXCIRPIOOFFOPWED
Message: []
[ { bundle:
     'UXQQYLIKUUWL9KFPFWXNKQCKQINDFEXLB9CHNVUY9VGQLDUAXWVHLQHK9YAYVLJJHVXCIRPIOOFFOPWED',
    error:
     RangeError: Source is too large
         at Int8Array.set (<anonymous>)
         at processBundle (/Users/ender/raam.client.js/lib/message.js:277:22)
         at Object.getMessage (/Users/ender/raam.client.js/lib/message.js:192:24) } ]
```

**Comment by jserv** [comment]
Close via commit bdd464eaeaaefde195380d435ee88baf0b2f02af
Revert to older IOTA packages to avoid API breakage
